spring:
  application:
    name: miniproject

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/MINIPROJECT
    username: hyfuser
    password: ${DB_PASSWORD}

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
      platform: postgresql

server:
  port: '8081'