spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  ai:
    openai:
      api-key: ${GITHUB_TOKEN}
      base-url: https://models.github.ai/inference
      chat:
        options:
          model: gpt-4o-mini

cloudflare:
  r2:
    endpoint: ${CLOUDFLARE_R2_ENDPOINT}
    access-key: ${CLOUDFLARE_R2_ACCESS_KEY}
    secret-key: ${CLOUDFLARE_R2_SECRET_KEY}
    bucket-name: ${CLOUDFLARE_R2_BUCKET_NAME}
